[workspace]
resolver = "2"
members = ["buildinfo", "imagesource", "vmdk", "e01", "rawdisk", "diskimage-nbd"]

[workspace.package]
license = "Apache-2.0"

[workspace.dependencies]
imagesource = { path = "imagesource" }
buildinfo = { path = "buildinfo" }
async-trait = "0.1.89"
foyer = { version = "0.22", features = ["serde"] }
futures = "0.3.31"
rust-s3 = { version = "0.37.1", features = ["tokio-rustls-tls"] }
aws-config = { version = "1.8", default-features = false, features = [
    "behavior-version-latest",
    "credentials-process",
    "rt-tokio",
    "sso",
    "rustls",
] }
aws-credential-types = "1.2"
bytesize = "2.3.1"
clap = { version = "4.5", features = ["derive"] }
criterion = "0.7"
hex = "0.4"
rand = "0.10"
sha1 = "0.10"
tempfile = "3.23.0"
thiserror = "2.0.12"
time = "0.3"
tokio = { version = "1.47.1", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "time"] }
url = "2.5.7"

[profile.release]
debug = false
lto = true
