[package]
name = "e01-rs"
version = "0.1.1"
authors = ["LevelBlue"]
edition = "2024"
autobins = false
exclude = [
    "/session*/",
    "/artifacts/",
]

[lib]
name = "e01"
path = "src/lib.rs"

[[bin]]
name = "e01verify"
path = "src/main.rs"

[[bin]]
name = "e01bench"
path = "src/bin/e01bench.rs"

[features]
capi = []

[dependencies]
imagesource.workspace = true
adler32 = "1.2"
byteorder = "1.5"
bytesize = "2.3.1"
clap = { version = "4.5", features = ["derive"] }
digest = "0.10.7"
flate2 = { version = "1", features = ["zlib-rs"] }
futures.workspace = true
glob = "0.3"
hex = "0.4"
itertools = "0.14.0"
#kaitai = { git = "https://github.com/kaitai-io/kaitai_struct_rust_runtime.git", branch = "master" }
kaitai = { git = "https://github.com/uckelman-sf/kaitai_struct_rust_runtime.git", branch = "master" }
md-5 = "0.10"
rand = "0.9"
rayon = "1.11.0"
rust-s3.workspace = true
sha1 = "0.10"
sha2 = "0.10"
simd-adler32 = "0.3"
tempfile.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
const_format = "0.2"
test-log = { version = "0.2.18", default-features = false, features = ["trace"] }
criterion = "0.7"

[[bench]]
name = "reader_bench"
path = "benches/reader_bench.rs"
harness = false
