[package]
name = "imagesource"
version = "0.1.0"
authors = ["LevelBlue"]
edition = "2024"

[dependencies]
async-trait.workspace = true
foyer.workspace = true
futures.workspace = true
rust-s3.workspace = true
aws-config.workspace = true
aws-credential-types.workspace = true
tempfile.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
percent-encoding = "2.3"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "cache_bench"
path = "benches/cache_bench.rs"
harness = false
