[package]
name = "rawdisk-rs"
version = "0.1.0"
authors = ["LevelBlue"]
edition = "2024"

[lib]
name = "rawdisk"
path = "src/lib.rs"

[[bin]]
name = "rawdiskverify"
path = "src/main.rs"

[features]
capi = []

[dependencies]
imagesource.workspace = true
bytesize.workspace = true
clap.workspace = true
hex.workspace = true
sha1.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
rand.workspace = true
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "reader_bench"
path = "benches/reader_bench.rs"
harness = false
